i18n:
  structure: multiple_files
  locales: [nl, fr]

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  repo: pmcp/sintLukasNuxt
  squash_merges: true

media_folder: public/assets/uploads
public_folder: /assets/uploads

publish_mode: editorial_workflow

collections:
  - label: 'Settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
            label: Site Description,
            name: sitedescription,
            widget: string,
            hint: 'This is used as descriptive text for links that link to this site',
          }
          - {
            label: Site Language,
            name: sitelang,
            widget: string,
            pattern: [ '^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")' ],
          }
      - label: 'Translations'
        name: 'translations'
        file: 'content/site/translations.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - label: "Translations"
            name: "translations"
            widget: "list"
            summary: '{{fields.fr}} - {{fields.nl}}'
            fields:
              - { label: FR, name: fr, widget: string }
              - { label: NL, name: nl, widget: string }
      - label: 'Navigation'
        name: 'navigation'
        file: 'content/site/navigation.json'
        format: 'json'
        i18n: true
        editor:
          preview: false
        fields:
          - label: 'Navigation item'
            name: 'navigation'
            widget: 'list'
            summary: '{{fields.page}}'
            collapsed: false
            fields:
              - label: "Label Fr"
                name: "labelfr"
                widget: "string"
              - label: "Label Nl"
                name: "labelnl"
                widget: "string"
              - label: "Page"
                name: "page"
                widget: "relation"
                collection: "pages"
                search_fields: [ "{{title}}" ]
                value_field: "{{slug}}"
                display_fields: [ "{{title}}" ]
  - name: 'pages'
    i18n: true
    label: 'Pages'
    label_singular: 'Page'
    folder: 'content'
    create: true
    format: 'frontmatter'
    # editor:
    #   preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true, i18n: true }
      - { label: 'Intro', name: 'intro', widget: 'text', i18n: true, required: false }
      - label: "Page layout"
        name: "layout"
        widget: "select"
        options:
          - { label: "Two columns", value: "0" }
          - { label: "One column", value: "1" }
      #      - { label: 'Content', name: 'body', widget: 'markdown', i18n: true }
      - label: 'Content'
        required: false
        i18n: true
        name: 'elements'
        label_singular: 'Element'
        widget: 'list'
        types:
          - label: 'Text'
            name: 'text'
            widget: object
            #            summary: '{{fields.header}}'
            fields:
              - { label: text, name: markdown, widget: markdown }
          - label: 'Images'
            name: 'images'
            widget: object
            fields:
              - label: "Layout"
                name: "layout"
                widget: "select"
                options:
                  - { label: "Masonry", value: 1 }
                  - { label: "Frame", value: 2 }
                  - { label: "Justified", value: 3 }
              - widget: list
                name: 'image'
                #                summary: '{{fields.fr}} - {{fields.nl}}'
                fields:
                  - label: "Image"
                    required: true
                    name: "image"
                    widget: "image"
                    choose_url: true
                    media_library:
                      config:
                        multiple: false
          - label: 'Buttons'
            name: 'buttons'
            widget: object
            fields:
              - widget: list
                name: 'button'
                fields:
                  - label: "label"
                    name: "label"
                    widget: "string"
                    required: true
                  - label: "Link"
                    name: "link"
                    required: false
                    widget: "string"
                  - label: "Download"
                    required: false
                    name: "download"
                    widget: "file"
                    media_library:
                      config:
                        multiple: false
                        max_file_size: 1024000 # in bytes, only for default media library
          - label: 'Reservation'
            name: 'reservation'
            widget: object
            fields:
              - widget: "hidden"
                name: "reservation"
                default: "reservation"
      - label: "Featured Image"
        required: false
        name: "image"
        widget: "image"
        choose_url: true
        i18n: true
        media_library:
          config:
            multiple: false